// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/whatthefar/monorepo-toolkit/pkg/interactor (interfaces: BuildProjectsPresenter)

// Package mock_interactor is a generated GoMock package.
package mock_interactor

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockBuildProjectsPresenter is a mock of BuildProjectsPresenter interface
type MockBuildProjectsPresenter struct {
	ctrl     *gomock.Controller
	recorder *MockBuildProjectsPresenterMockRecorder
}

// MockBuildProjectsPresenterMockRecorder is the mock recorder for MockBuildProjectsPresenter
type MockBuildProjectsPresenterMockRecorder struct {
	mock *MockBuildProjectsPresenter
}

// NewMockBuildProjectsPresenter creates a new mock instance
func NewMockBuildProjectsPresenter(ctrl *gomock.Controller) *MockBuildProjectsPresenter {
	mock := &MockBuildProjectsPresenter{ctrl: ctrl}
	mock.recorder = &MockBuildProjectsPresenterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBuildProjectsPresenter) EXPECT() *MockBuildProjectsPresenterMockRecorder {
	return m.recorder
}

// AllBuildSucceeded mocks base method
func (m *MockBuildProjectsPresenter) AllBuildSucceeded() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AllBuildSucceeded")
}

// AllBuildSucceeded indicates an expected call of AllBuildSucceeded
func (mr *MockBuildProjectsPresenterMockRecorder) AllBuildSucceeded() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllBuildSucceeded", reflect.TypeOf((*MockBuildProjectsPresenter)(nil).AllBuildSucceeded))
}

// BuildFailedFor mocks base method
func (m *MockBuildProjectsPresenter) BuildFailedFor(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BuildFailedFor", arg0)
}

// BuildFailedFor indicates an expected call of BuildFailedFor
func (mr *MockBuildProjectsPresenterMockRecorder) BuildFailedFor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildFailedFor", reflect.TypeOf((*MockBuildProjectsPresenter)(nil).BuildFailedFor), arg0)
}

// BuildSkippedFor mocks base method
func (m *MockBuildProjectsPresenter) BuildSkippedFor(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BuildSkippedFor", arg0)
}

// BuildSkippedFor indicates an expected call of BuildSkippedFor
func (mr *MockBuildProjectsPresenterMockRecorder) BuildSkippedFor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildSkippedFor", reflect.TypeOf((*MockBuildProjectsPresenter)(nil).BuildSkippedFor), arg0)
}

// BuildTriggeredFor mocks base method
func (m *MockBuildProjectsPresenter) BuildTriggeredFor(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BuildTriggeredFor", arg0)
}

// BuildTriggeredFor indicates an expected call of BuildTriggeredFor
func (mr *MockBuildProjectsPresenterMockRecorder) BuildTriggeredFor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildTriggeredFor", reflect.TypeOf((*MockBuildProjectsPresenter)(nil).BuildTriggeredFor), arg0)
}

// KillBuildErrorFor mocks base method
func (m *MockBuildProjectsPresenter) KillBuildErrorFor(arg0 error, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "KillBuildErrorFor", arg0, arg1)
}

// KillBuildErrorFor indicates an expected call of KillBuildErrorFor
func (mr *MockBuildProjectsPresenterMockRecorder) KillBuildErrorFor(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KillBuildErrorFor", reflect.TypeOf((*MockBuildProjectsPresenter)(nil).KillBuildErrorFor), arg0, arg1)
}

// KillingBuildsFor mocks base method
func (m *MockBuildProjectsPresenter) KillingBuildsFor(arg0 []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "KillingBuildsFor", arg0)
}

// KillingBuildsFor indicates an expected call of KillingBuildsFor
func (mr *MockBuildProjectsPresenterMockRecorder) KillingBuildsFor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KillingBuildsFor", reflect.TypeOf((*MockBuildProjectsPresenter)(nil).KillingBuildsFor), arg0)
}

// NoBuildTriggeredFor mocks base method
func (m *MockBuildProjectsPresenter) NoBuildTriggeredFor(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NoBuildTriggeredFor", arg0)
}

// NoBuildTriggeredFor indicates an expected call of NoBuildTriggeredFor
func (mr *MockBuildProjectsPresenterMockRecorder) NoBuildTriggeredFor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NoBuildTriggeredFor", reflect.TypeOf((*MockBuildProjectsPresenter)(nil).NoBuildTriggeredFor), arg0)
}

// NotFinishedBuildsKilled mocks base method
func (m *MockBuildProjectsPresenter) NotFinishedBuildsKilled() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotFinishedBuildsKilled")
}

// NotFinishedBuildsKilled indicates an expected call of NotFinishedBuildsKilled
func (mr *MockBuildProjectsPresenterMockRecorder) NotFinishedBuildsKilled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotFinishedBuildsKilled", reflect.TypeOf((*MockBuildProjectsPresenter)(nil).NotFinishedBuildsKilled))
}

// ThrowError mocks base method
func (m *MockBuildProjectsPresenter) ThrowError(arg0 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ThrowError", arg0)
}

// ThrowError indicates an expected call of ThrowError
func (mr *MockBuildProjectsPresenterMockRecorder) ThrowError(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ThrowError", reflect.TypeOf((*MockBuildProjectsPresenter)(nil).ThrowError), arg0)
}

// Timeout mocks base method
func (m *MockBuildProjectsPresenter) Timeout() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Timeout")
}

// Timeout indicates an expected call of Timeout
func (mr *MockBuildProjectsPresenterMockRecorder) Timeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Timeout", reflect.TypeOf((*MockBuildProjectsPresenter)(nil).Timeout))
}

// WaitingFor mocks base method
func (m *MockBuildProjectsPresenter) WaitingFor(arg0 []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WaitingFor", arg0)
}

// WaitingFor indicates an expected call of WaitingFor
func (mr *MockBuildProjectsPresenterMockRecorder) WaitingFor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitingFor", reflect.TypeOf((*MockBuildProjectsPresenter)(nil).WaitingFor), arg0)
}
